package uz.muhsinov.irregularverbs

import android.annotation.SuppressLint
import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import android.speech.tts.TextToSpeech
import android.text.Editable
import android.text.TextWatcher
import android.view.View
import android.widget.PopupMenu
import androidx.appcompat.app.AppCompatDelegate
import uz.muhsinov.irregularverbs.adapters.RvAdapter
import uz.muhsinov.irregularverbs.databinding.ActivityMainBinding
import uz.muhsinov.irregularverbs.models.English
import java.util.*

class MainActivity : AppCompatActivity() {

    lateinit var rvAdapter: RvAdapter
    lateinit var textToSpeech: TextToSpeech
    lateinit var listEnglish: ArrayList<English>
    lateinit var list1: ArrayList<String>
    lateinit var list2: ArrayList<String>
    lateinit var list3: ArrayList<String>
    lateinit var list4: ArrayList<String>
    lateinit var list: ArrayList<English>
    lateinit var binding: ActivityMainBinding

    @SuppressLint("ClickableViewAccessibility")
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_NO)
        binding = ActivityMainBinding.inflate(layoutInflater)
        setContentView(binding.root)
        listEnglish = ArrayList()
        list = ArrayList()


        loadList1()
        loadList2()
        loadList3()
        loadList4()

        var count = 0

        while (count <= 108) {
            list.add(English(list1[count], list2[count], list3[count], list4[count]))
            count++
        }




        binding.myEdtSearch.addTextChangedListener(object : TextWatcher {
            override fun beforeTextChanged(s: CharSequence?, start: Int, count: Int, after: Int) {

            }

            override fun onTextChanged(s: CharSequence?, start: Int, before: Int, count: Int) {

            }

            override fun afterTextChanged(s: Editable?) {
                val searchList = searchList(s.toString())
                listEnglish.clear()
                listEnglish.addAll(searchList)
                adapterRecycler(listEnglish)
            }
        })

        adapterRecycler(list)

        textToSpeech = TextToSpeech(binding.root.context, TextToSpeech.OnInitListener {

            // if No error is found then only it will run
            if (it != TextToSpeech.ERROR) {
                // To Choose language of speech
                textToSpeech.language = Locale.ENGLISH
            }
        })


    }
    fun adapterRecycler(listEnglish: ArrayList<English>) {
        rvAdapter = RvAdapter(binding.root.context, object : RvAdapter.RvClick {
            override fun onClick(english: English, view: View) {
                val popupMenu = PopupMenu(binding.root.context, view)
                popupMenu.inflate(R.menu.item_child)
                popupMenu.setOnMenuItemClickListener {
                    when (it.itemId) {
                        R.id.menu_type_1 -> {
                            val text = listEnglish[listEnglish.indexOf(english)].type1
                            textToSpeech.speak(text, TextToSpeech.QUEUE_FLUSH, null)
                        }
                        R.id.menu_type_2 -> {
                            val text = listEnglish[listEnglish.indexOf(english)].type2
                            textToSpeech.speak(text, TextToSpeech.QUEUE_FLUSH, null)
                        }
                        R.id.menu_type_3 -> {
                            val text = listEnglish[listEnglish.indexOf(english)].type3
                            textToSpeech.speak(text, TextToSpeech.QUEUE_FLUSH, null)
                        }
                    }
                    true
                }
                popupMenu.show()
            }

        }, listEnglish)
        binding.continer1.adapter = rvAdapter
    }

    fun searchList(searchText: String): ArrayList<English> {
        val listEnglis = ArrayList<English>()
        val list3 = list.filter {
//            it.type1.toUpperCase().startsWith(searchText.toUpperCase())||
//                    it.type2.toLowerCase().startsWith(searchText.toLowerCase()) ||
//                    it.type3.toLowerCase()
//                        .startsWith(searchText.toLowerCase()) ||
            it.type1.toUpperCase().startsWith(searchText.toUpperCase())
        }
        listEnglis.addAll(list3)
        return listEnglis
    }


    fun loadList1() {
        list1 = ArrayList()
        list1.add("Be")
        list1.add("Bear")
        list1.add("Beat")
        list1.add("Become")
        list1.add("Begin")
        list1.add("Bite")
        list1.add("Blow")
        list1.add("Break")
        list1.add("Bring")
        list1.add("Build")
        list1.add("Burn")
        list1.add("Burst")
        list1.add("Buy")
        list1.add("Can")
        list1.add("Catch")
        list1.add("Choose")
        list1.add("Come")
        list1.add("Cost")
        list1.add("Cut")
        list1.add("Deal")
        list1.add("Dig")
        list1.add("Do")
        list1.add("Draw")
        list1.add("Dream")
        list1.add("Drink")
        list1.add("Drive")
        list1.add("Eat")
        list1.add("Fall")
        list1.add("Feed")
        list1.add("Feel")
        list1.add("Fight")
        list1.add("Find")
        list1.add("Fly")
        list1.add("Forbid")
        list1.add("Forget")
        list1.add("Forgive")
        list1.add("Freeze")
        list1.add("Get")
        list1.add("Give")
        list1.add("Go")
        list1.add("Grow")
        list1.add("Hang")
        list1.add("Have")
        list1.add("Hear")
        list1.add("Hide")
        list1.add("Hit")
        list1.add("Hold")
        list1.add("Hurt")
        list1.add("Keep")
        list1.add("Know")
        list1.add("Lay")
        list1.add("Lead")
        list1.add("Learn")
        list1.add("Leave")
        list1.add("Lend")
        list1.add("Let")
        list1.add("Lie")
        list1.add("Light")
        list1.add("Lose")
        list1.add("Make")
        list1.add("Mean")
        list1.add("Meet")
        list1.add("Pay")
        list1.add("Put")
        list1.add("Read")
        list1.add("Ride")
        list1.add("Ring")
        list1.add("Rise")
        list1.add("Run")
        list1.add("Say")
        list1.add("See")
        list1.add("Sell")
        list1.add("Send")
        list1.add("Set")
        list1.add("Sew")
        list1.add("Shake")
        list1.add("Shine")
        list1.add("Shoot")
        list1.add("Show")
        list1.add("Shut")
        list1.add("Sing")
        list1.add("Sit")
        list1.add("Sleep")
        list1.add("Smell")
        list1.add("Speak")
        list1.add("Spell")
        list1.add("Spend")
        list1.add("Spill")
        list1.add("Spoil")
        list1.add("Spread")
        list1.add("Stand")
        list1.add("Steal")
        list1.add("Stick")
        list1.add("Sting")
        list1.add("Strike")
        list1.add("Swear")
        list1.add("Sweep")
        list1.add("Swim")
        list1.add("Take")
        list1.add("Teach")
        list1.add("Tear")
        list1.add("Tell")
        list1.add("Think")
        list1.add("Throw")
        list1.add("Understand")
        list1.add("Wake")
        list1.add("Wear")
        list1.add("Win")
        list1.add("Write")

    }

    fun loadList2() {
        list2 = ArrayList()
        list2.add("  was")
        list2.add("  bore")
        list2.add("  beat")
        list2.add("  became")
        list2.add("  began")
        list2.add("  bit")
        list2.add("  blew")
        list2.add("  broke")
        list2.add("  brought")
        list2.add("  built")
        list2.add("  burnt")
        list2.add("  burst")
        list2.add("  bought")
        list2.add("  could")
        list2.add("  caught")
        list2.add("  chose")
        list2.add("  came")
        list2.add("  cost")
        list2.add("  cut")
        list2.add("  dealt")
        list2.add("  dug")
        list2.add("  did")
        list2.add("  drew")
        list2.add("  dreamt")
        list2.add("  drank")
        list2.add("  drove")
        list2.add("  ate")
        list2.add("  fell")
        list2.add("  fed")
        list2.add("  felt")
        list2.add("  fought")
        list2.add("  found")
        list2.add("  flew")
        list2.add("  forbade")
        list2.add("  forgot")
        list2.add("  forgave")
        list2.add("  froze")
        list2.add("  got")
        list2.add("  gave")
        list2.add("  went")
        list2.add("  grew")
        list2.add("  hung ")
        list2.add("  had")
        list2.add("  heard")
        list2.add("  hid")
        list2.add("  hit")
        list2.add("  held")
        list2.add("  hurt")
        list2.add("  kept")
        list2.add("  knew")
        list2.add("  laid")
        list2.add("  led")
        list2.add("  learnt")
        list2.add("  left")
        list2.add("  lent")
        list2.add("  let")
        list2.add("  lay")
        list2.add("  lit")
        list2.add("  lost")
        list2.add("  made")
        list2.add("  meant")
        list2.add("  met")
        list2.add("  paid")
        list2.add("  put")
        list2.add("  read")
        list2.add("  rode")
        list2.add("  fang")
        list2.add("  rose")
        list2.add("  ran")
        list2.add("  said")
        list2.add("  saw")
        list2.add("  sold")
        list2.add("  sent")
        list2.add("  set")
        list2.add("  sewed")
        list2.add("  shook")
        list2.add("  shone")
        list2.add("  shot")
        list2.add("  showed")
        list2.add("  shut")
        list2.add("  sang")
        list2.add("  sat")
        list2.add("  slept")
        list2.add("  smelt")
        list2.add("  spoke")
        list2.add("  spelt")
        list2.add("  spent")
        list2.add("  spilt")
        list2.add("  spoilt")
        list2.add("  spread")
        list2.add("  stood")
        list2.add("  stole")
        list2.add("  stuck")
        list2.add("  stung")
        list2.add("  struck")
        list2.add("  swore")
        list2.add("  swept")
        list2.add("  swam")
        list2.add("  took")
        list2.add("  taught")
        list2.add("  tore")
        list2.add("  told")
        list2.add("  thought")
        list2.add("  threw")
        list2.add("  undestood")
        list2.add("  woke")
        list2.add("  wore")
        list2.add("  won")
        list2.add("  wrote")

    }

    fun loadList3() {
        list3 = ArrayList()
        list3.add("  been")
        list3.add("  born")
        list3.add("  beaten")
        list3.add("  become")
        list3.add("  begun")
        list3.add("  bitten")
        list3.add("  blown")
        list3.add("  broken")
        list3.add("  brought")
        list3.add("  built")
        list3.add("  burnt")
        list3.add("  burst")
        list3.add("  bought")
        list3.add("  (been able to)")
        list3.add("  caught")
        list3.add("  chosen")
        list3.add("  come")
        list3.add("  cost")
        list3.add("  cut")
        list3.add("  dealt")
        list3.add("  dug")
        list3.add("  done")
        list3.add("  drawn")
        list3.add("  dreamt")
        list3.add("  drunk")
        list3.add("  driven")
        list3.add("  eaten")
        list3.add("  fallen")
        list3.add("  fed")
        list3.add("  felt")
        list3.add("  fought")
        list3.add("  found")
        list3.add("  flown")
        list3.add("  forbidden")
        list3.add("  forgotten")
        list3.add("  forgiven")
        list3.add("  frozen")
        list3.add("  got")
        list3.add("  given")
        list3.add("  gone")
        list3.add("  grown")
        list3.add("  hung")
        list3.add("  had")
        list3.add("  heard")
        list3.add("  hidden")
        list3.add("  hit")
        list3.add("  held")
        list3.add("  hurt")
        list3.add("  kept")
        list3.add("  known")
        list3.add("  laid")
        list3.add("  led")
        list3.add("  learnt")
        list3.add("  left")
        list3.add("  lent")
        list3.add("  let")
        list3.add("  lain")
        list3.add("  lit")
        list3.add("  lost")
        list3.add("  made")
        list3.add("  meant")
        list3.add("  met")
        list3.add("  paid")
        list3.add("  put")
        list3.add("  read")
        list3.add("  ridden")
        list3.add("  fung")
        list3.add("  risen")
        list3.add("  run")
        list3.add("  said")
        list3.add("  seen")
        list3.add("  sold")
        list3.add("  sent")
        list3.add("  set")
        list3.add("  sewn")
        list3.add("  shaken")
        list3.add("  shone")
        list3.add("  shot")
        list3.add("  shown")
        list3.add("  shut")
        list3.add("  sung")
        list3.add("  sat")
        list3.add("  slept")
        list3.add("  smelt")
        list3.add("  spoken")
        list3.add("  spelt")
        list3.add("  spent")
        list3.add("  spilt")
        list3.add("  spoilt")
        list3.add("  spread")
        list3.add("  stood")
        list3.add("  stolen")
        list3.add("  stuck")
        list3.add("  stung")
        list3.add("  struck")
        list3.add("  swore")
        list3.add("  swept")
        list3.add("  swum")
        list3.add("  taken")
        list3.add("  taught")
        list3.add("  torn")
        list3.add("  told")
        list3.add("  thought")
        list3.add("  thrown")
        list3.add("  undestood")
        list3.add("  woken")
        list3.add("  worn")
        list3.add("  won")
        list3.add("  written")

    }

    fun loadList4() {
        list4 = ArrayList()
        list4.add("bo'lmoq")
        list4.add("tug'ulmoq")
        list4.add("urmoq")
        list4.add("bo'lmoq")
        list4.add("boshlamoq")
        list4.add("tishlamoq")
        list4.add("puflamoq")
        list4.add("sindirmoq")
        list4.add("olib kelmoq")
        list4.add("qurmoq")
        list4.add("yonmoq, kuymoq")
        list4.add("yoqilmoq")
        list4.add("sotib olmoq")
        list4.add("qila olmoq")
        list4.add("tutmoq")
        list4.add("tanlamoq")
        list4.add("kelmoq")
        list4.add("narx belgilamoq")
        list4.add("kesmoq")
        list4.add("taqsimlamoq")
        list4.add("kavlamoq")
        list4.add("qilmoq")
        list4.add("chizmoq")
        list4.add("orzu qilmoq")
        list4.add("ichmoq")
        list4.add("haydamoq")
        list4.add("yemoq")
        list4.add("qulamoq")
        list4.add("boqmoq")
        list4.add("his qilmoq")
        list4.add("jang qilmoq")
        list4.add("topmoq")
        list4.add("uchmoq")
        list4.add("ta'qiqlamoq")
        list4.add("unutmoq")
        list4.add("kechirmoq")
        list4.add("muzlatmoq")
        list4.add("olmoq")
        list4.add("bermoq")
        list4.add("bormoq")
        list4.add("o'smoq")
        list4.add("osib qo'ymoq")
        list4.add("ega bo'lmoq")
        list4.add("eshitmoq")
        list4.add("yashirmoq")
        list4.add("zarba bermoq (urmoq)")
        list4.add("ushlamoq (tutmoq)")
        list4.add("zarar yetmoq")
        list4.add("saqlamoq")
        list4.add("bilmoq")
        list4.add("qo'ymoq, joylamoq")
        list4.add("olib bormoq")
        list4.add("o'rganmoq")
        list4.add("tark etmoq, qoldirmoq")
        list4.add("qarz bermoq")
        list4.add("ruxsat bermoq")
        list4.add("yotmoq")
        list4.add("yoqmoq")
        list4.add("yo'qotmoq")
        list4.add("qilmoq, yaratmoq")
        list4.add("ma'no bildirmoq")
        list4.add("uchratmoq")
        list4.add("to'lamoq")
        list4.add("qo'ymoq")
        list4.add("o'qimoq")
        list4.add("minmoq")
        list4.add("qo'ng'iroq qilmoq")
        list4.add("ko'tarilmoq")
        list4.add("yugurmoq")
        list4.add("gapirmoq")
        list4.add("ko'rmoq")
        list4.add("sotmoq")
        list4.add("jo'natmoq")
        list4.add("o'rnatmoq")
        list4.add("tikmoq")
        list4.add("qaltiramoq")
        list4.add("nur sochmoq")
        list4.add("otmoq")
        list4.add("ko'rsatmoq")
        list4.add("berkitmoq")
        list4.add("kuylamoq")
        list4.add("o'tirmoq")
        list4.add("uxlamoq")
        list4.add("hidlamoq")
        list4.add("suhbatlashmoq")
        list4.add("xarflab aytmoq")
        list4.add("sarflamoq")
        list4.add("to'k(il)moq")
        list4.add("buzmoq")
        list4.add("tarqalmoq")
        list4.add("turmoq")
        list4.add("o'girlamoq")
        list4.add("yopishtirmoq")
        list4.add("chaqmoq")
        list4.add("urmoq")
        list4.add("so'kinmoq, qasam ichmoq")
        list4.add("supurmoq")
        list4.add("suzmoq")
        list4.add("olmoq")
        list4.add("o'rgatmoq")
        list4.add("yirtmoq")
        list4.add("aytib bermoq")
        list4.add("o'ylamoq")
        list4.add("otmoq")
        list4.add("tushumoq")
        list4.add("uyg'otmoq")
        list4.add("kiyib yurmoq")
        list4.add("yutmoq")
        list4.add("yozmoq")

    }
}